services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env   # <- loads your environment variables
    volumes:
      - .:/app

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env   # <- also loads env variables for DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
